### ISSUE TITLE
Edit user profile

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#128]
Missing part in user-form: edit user; it doesn't work at the moment

**Comment by kilchenmann** [comment]
As described in the milestone: End of March

**Comment by kilchenmann** [comment]
@subotic is it possible, that a system admin can change the password from another user? I couldn't find the correct way in Knora.
Changing the own password is not the problem and works fine since today.

**Comment by subotic** [comment]
Yes, I think so.

**Comment by kilchenmann** [comment]
Please implement changing user password by system administrator.
