### ISSUE TITLE
npm modules of salsah

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#140]
I'm working on the creation of single salsah modules, which will be published on npm. I already added a user called [@salsah](https://www.npmjs.com/~salsah). The salsah modules should named as `@salsah/[module-name]`

I'm following the npm principe of angular and material and playing around with [Angular 2 Library Generator](https://github.com/jvandemo/generator-angular2-library) and [ng-packagr](https://www.npmjs.com/package/ng-packagr). In the future angular/cli will implement an own library service. Get more information here: https://github.com/angular/angular-cli/issues/6510

**Comment by tobiasschweizer** [comment]
when you have found how this works, please let me know :-)

I tried that here but failed https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter

this is an NgModule that goes to npmjs.com

**Comment by kilchenmann** [comment]
I tested Angular 2 Library Generator. It worked fine and I [published my test module on npm](https://www.npmjs.com/package/ng-horo)

**Comment by kilchenmann** [comment]
We should use ng-packagr! There's a nice tutorial how to use it: https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e

**Comment by kilchenmann** [comment]
Our own node modules will be in a scope called [@salsah](https://npmjs.com/~salsah).
You will find some documentation here: 
- [npm-scope](https://docs.npmjs.com/misc/scope#publishing-public-scoped-packages-to-the-public-npm-registry)
- [How to Work with Scoped Packages](https://docs.npmjs.com/getting-started/scoped-packages)

**Comment by kilchenmann** [comment]
TODO:

- [ ] create npm scope for [@salsah](https://www.npmjs.com/~salsah)
- [ ] upload service modules: https://www.npmjs.com/package/@salsah/services

**Comment by kilchenmann** [comment]
I started with an own repository for the salsah modules here: 
https://github.com/dhlab-basel/salsah-modules

And two modules are already published [on npm](https://www.npmjs.com/~salsah)

**Comment by sofiag** [comment]
ok!
