### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#142]
We have to implement (or doing it by ourselves) an infinite/endless scroll module. 
e.g. https://github.com/orizens/ngx-infinite-scroll
or https://codeburst.io/angular-2-simple-infinite-scroller-directive-with-rxjs-observables-a989b12d4fb1

**Comment by tobiasschweizer** [comment]
When scrolling in a list of results, the next page of results should be fetched using offset.

**Comment by kilchenmann** [comment]
I'm working on it on branch [wip/infinite-scroll-#142](https://github.com/dhlab-basel/Salsah/tree/wip/infinite-scroll-%23142)
