### ISSUE TITLE
show number of all results (count query)

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#143]
For each search, a count query is performed to get the total number of results (not just the number of results returned by the first page of results).

The number of all results should be displayed, so the user knows that there are more results he could get.

**Comment by tobiasschweizer** [comment]
count queries are implemented with this PR: https://github.com/dhlab-basel/Salsah/pull/109

**Comment by tobiasschweizer** [comment]
for now, results are displayed here: `src/app/view/modules/listing/resources-list/resources-list.component.html`

```

<!-- show the results -->
<div *ngIf="!isLoading && !errorMessage; else errorMsg">

    <div *ngIf="numberOfItems !== 0; else noData" [ngSwitch]="listType">
        <div>{{numberOfAllResults}}</div>

        <!-- show as table if listType === table -->
        <table *ngSwitchCase="'table'" class="salsah-table">
        </table>
```

**Comment by kilchenmann** [comment]
This should be fixed in the salsah ng6-update.
