### ISSUE TITLE
CSS bug in search result list

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#146]
When displaying a list of resources (results of extended search) with several properties, the design is broken

<img width="1401" alt="result-list" src="https://user-images.githubusercontent.com/6000023/35144657-6e16e748-fd05-11e7-8374-bcf3aa1bac1c.png">

This must be related to the HTML template and CSS.

**Comment by tobiasschweizer** [comment]
also HTML should be shown as innerHTML

<img width="1047" alt="html_in_results" src="https://user-images.githubusercontent.com/6000023/35214137-6c966abc-ff60-11e7-9b2e-edd4f0af2070.png">

**Comment by tobiasschweizer** [comment]
and it would be cool to have a highlight for fulltext search results :-)

**Comment by kilchenmann** [comment]
I'm not sure if we should fix it with a css-styling solution. I will look for a mix of styling and trimming...

> and it would be cool to have a highlight for fulltext search results :-)

The people from NIE-INE (@janCstoffregen) implemented a highlight module in their [raeber-website](https://github.com/nie-ine/raeber-website). Perhaps we can use the same?

**Comment by janCstoffregen** [comment]
Hi, yes, please feel free to use it, here it is:

https://github.com/nie-ine/raeber-website/blob/a26146e0c87c9ab529d03c45f2c24592a677990f/src/client/app/shared/textgrid/textgrid.component.html#L29

https://github.com/nie-ine/raeber-website/blob/master/src/client/app/shared/textgrid/textgrid.component.ts#L59

It is for more than one search term, the search terms are highlighted in different colours.


and the css... https://github.com/nie-ine/raeber-website/blob/a26146e0c87c9ab529d03c45f2c24592a677990f/src/client/css/main.css

and where it is used in html: https://github.com/nie-ine/raeber-website/blob/a26146e0c87c9ab529d03c45f2c24592a677990f/src/client/app/shared/textgrid/textgrid.component.html#L29

**Comment by tobiasschweizer** [comment]
@janCstoffregen thx, I will try that!

**Comment by janCstoffregen** [comment]
I'm glad if it helps!

**Comment by tobiasschweizer** [comment]
Could this be made available as an npm module? Otherwise I would have to copy and paste the code.

I have provided an own implementation of `DateAdapter` https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter/tree/develop/src/app/modules/jdnconvertiblecalendardateadapter and made it available as an npm module: https://www.npmjs.com/package/jdnconvertiblecalendardateadapter

In Salsah, you just have to mention the module in `package.json` as a dependency.

**Comment by janCstoffregen** [comment]
Hi, yes, I'll transform it to an npm module, thanks for the hint, that's a good idea! I should be done latest next week and I'll let you know when I'm done, ok?

**Comment by kilchenmann** [comment]
What's the status of this issue? @janCstoffregen have you build a npm module yet?

**Comment by janCstoffregen** [comment]
@tobiasschweizer and @benjamingeer wanted to do it on the server side, so I have not continued here.

**Comment by janCstoffregen** [comment]
as I understood it.

**Comment by kilchenmann** [comment]
ah okay; great. Thanks for answering.
Then it's the topic, which I also already discussed with @tobiasschweizer.

**Comment by kilchenmann** [comment]
This will be done on server side. Depends on https://github.com/dhlab-basel/Knora/issues/913, which depends on https://github.com/dhlab-basel/Knora/issues/926.
