### ISSUE TITLE
Feedback Form for GUI

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#147]
Add a form where the user can submit feedback (an email is generated)

Spam protection should be provided

the exact URL should be sent so it will be easier to find out what the reported problem is about

**Comment by tobiasschweizer** [comment]
https://medium.com/@markgoho/create-a-contact-form-in-angular-using-cloud-functions-for-firebase-5e390bdf5600

**Comment by tobiasschweizer** [comment]
https://progblog.io/How-to-Using-Angular-4-and-Cloud-Functions-for-Firebase-to-Build-a-Contact-Form-PT-1/

**Comment by SepidehAlassi** [comment]
@tobiasschweizer we can close this right?
