### ISSUE TITLE
era is not visible in salsah

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Salsah#149]
when a knora Date has era (like JULIAN:325 BC) era is not shown in salsah, just calendar type and date is visible.

**Comment by tobiasschweizer** [comment]
I think BC support is just not implemented yet. 

This would have to happen here: https://github.com/dhlab-basel/Salsah/blob/00f930cb93a5a136ad50680d46226f145d76a0d0/src/app/model/webapi/knora/v2/read-property-item.ts#L147

We could do that next week.

**Comment by tobiasschweizer** [comment]
We should also check if the BC indicator is correctly submitted in the v2 JSON-LD so it can go in the constructor as a parameter when instantiating a date: https://github.com/dhlab-basel/Salsah/blob/00f930cb93a5a136ad50680d46226f145d76a0d0/src/app/model/webapi/knora/v2/convert-jsonld.ts#L109
