### ISSUE TITLE
CSS issue with search bar

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#179]
When activating the extended search, the form has no background-color.

Also when entering text in the full text search form, it looks strange. I think this is a CSS issue.

<img width="1342" alt="screen shot 2018-03-01 at 10 14 26 am" src="https://user-images.githubusercontent.com/6000023/36836363-6715a958-1d39-11e8-8d3b-60266d549de2.png">

**Comment by kilchenmann** [comment]
In which branch?

**Comment by tobiasschweizer** [comment]
develop

**Comment by kilchenmann** [comment]
I can fix it today

**Comment by tobiasschweizer** [comment]
Great, thanks a lot!

Ping me if I should test something.

**Comment by kilchenmann** [comment]
It was my mistake. I thought the css code is redundant.

**Comment by tobiasschweizer** [comment]
no worries ;-)

I will test it asap.
