### ISSUE TITLE
close button for dialog

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#187]
Dialog is used in the following directives and components. The close button is missing.

- src/app/view/modules/other/mathjax.directive.ts
- src/app/view/modules/form/contact-form/contact-form.component.ts

**Comment by kilchenmann** [comment]
Should I work in your branch (which one) or should I make a new one?

**Comment by tobiasschweizer** [comment]
We would need a close button here too: https://github.com/dhlab-basel/Salsah/blob/0e4f5d00d8b534237470cbba6af948866421240c/src/app/view/modules/other/mathjax.directive.ts#L44
