### ISSUE TITLE
Remove Looked For from template

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Salsah#188]
Looked For and its corresponding URI should be just visible in case of full text search

**Comment by SepidehAlassi** [comment]
![screen shot 2018-03-06 at 17 24 32](https://user-images.githubusercontent.com/8567642/37044324-71dc5264-2163-11e8-8dd8-a27c61cf5b58.png)

**Comment by kilchenmann** [comment]
I can try to fix it
