### ISSUE TITLE
Building with '--prod' fails

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Salsah#198]
Building Salsah2 for production 

```
$ ng build --prod --env=prod
```

fails with the following error:

```
ERROR in : Unexpected value 'MatJDNConvertibleCalendarDateAdapterModule in /Users/subotic/_github.com/Salsah/node_modules/jdnconvertiblecalendardateadapter/dist/index.d.ts' imported by the module 'AppModule in /Users/subotic/_github.com/Salsah/src/app/app.module.ts'. Please add a @NgModule annotation.
```

**Comment by subotic** [comment]
@tobiasschweizer this sounds like JDN. Do you maybe know what the problem could be?

**Comment by kilchenmann** [comment]
Why you're using the --prod flag? It works with

```
$ ng build --env=prod
```

The production flag is already set in environment.prod.ts.

I know there are some issues with the --prod flag in angular-cli. But your command should be the same as mine. It's described here: https://www.npmjs.com/package/angular-cli#creating-a-build 
So, it's strange that one case is running and the other one isn't.

**Comment by subotic** [comment]
> Why you're using the --prod flag?

Because this is what should be used when building for production. Please see https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds

I know it works without the `--prod` flag. But then it is the same as running with `--dev`.

**Comment by subotic** [comment]
> The production flag is already set in environment.prod.ts.

I don't think that this does anything. It's simply for easy checking of the environment during runtime, e.g.:

```
if (environment.production) {
  ...
}
```

or 

```
if (isDevMode()) {
      console.log('👋 Development!');
} else {
      console.log('💪 Production!');
}
```

**Comment by subotic** [comment]
I think that this is related to https://github.com/angular/angular/issues/15763. Apparently, defining `"@angular/core": "^5.1.0"` in `package.json` of `JDNConvertibleCalendarDateAdapter`, can cause problems with `Salsah2` which uses `"@angular/core": "^5.2.2"`. The solution is to set it like this `"@angular/core": ">=5.1.0"`.

**Comment by subotic** [comment]
relevant: https://github.com/dhlab-basel/JDNConvertibleCalendarDateAdapter/pull/4

**Comment by tobiasschweizer** [comment]
`/Users/tobi/gitreps/salsah_github/node_modules/jdnconvertiblecalendardateadapter/dist/index.d.ts`

```
import {NgModule} from '@angular/core';
import {DateAdapter, MAT_DATE_FORMATS, MAT_DATE_LOCALE, MAT_DATE_LOCALE_PROVIDER} from '@angular/material';
import {MAT_JDN_DATE_FORMATS} from 'jdnconvertiblecalendardateadapter/dist/JDNConvertibleCalendar-date-formats';
import {JDNConvertibleCalendarDateAdapter} from 'jdnconvertiblecalendardateadapter';

@NgModule({
    providers: [
        MAT_DATE_LOCALE_PROVIDER,
        {provide: DateAdapter, useClass: JDNConvertibleCalendarDateAdapter, deps: [MAT_DATE_LOCALE]}
    ]
})
export declare class JDNConvertibleCalendarDateAdapterModule {
}

@NgModule({
    imports: [JDNConvertibleCalendarDateAdapterModule],
    providers: [{provide: MAT_DATE_FORMATS, useValue: MAT_JDN_DATE_FORMATS}],
})
export declare class MatJDNConvertibleCalendarDateAdapterModule {
}
export { JDNConvertibleCalendarDateAdapter } from './JDNConvertibleCalendarDateAdapter';
```

**Comment by subotic** [comment]
final build command: `ng build --prod --env=prod --build-optimizer`

**Comment by subotic** [comment]
interesting view:

<img width="1908" alt="screenshot 2018-03-15 11 48 39" src="https://user-images.githubusercontent.com/400790/37458957-e4555dec-2846-11e8-99c1-7dd9ea3f94af.png">

This is a screenshot of a clickable map which you can generate with the following steps:

```
$ ng build --prod --sourcemaps
$ node_modules/.bin/source-map-explorer dist/main.*.bundle.js
```

The `source-map-explorer` package needs to be installed. I have added it to `devDependencies` in the `wip/fix-prod-build`.

**Comment by kilchenmann** [comment]
btw. --env doesn't exist anymore in Angular 6 cli. It's now --configuration or -c
I will document this in the PR #292
