### ISSUE TITLE
Pressing 'esc' while inside search field does not behave as expected

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Salsah#203]
- when clicking inside search field, then the history thingy* shows up. clicking here 'esc', doesn't close it.
- clicking on the 'x' closes the history thingy. pressing now 'esc' opens history thingy again.
- history thingy opens even when there is nothing to show. size should adapt to shown content, i.e. no content, no history thingy.

*Please feel free to exchange 'thingy' with the right name.

**Comment by kilchenmann** [comment]
Ok..I have to fix the issue with the esc key.

We can name 'thingy' as panel or drawer. At the end it shouldn't contain the search history only, it can also be used for autocomplete (suggest-as-you-type) or the set a filter (project). This is the reason why it's open even if it's empty. At the end it wouldn't be empty anymore. The first ideas of the search panel are described in the [Documentation](https://dhlab-basel.github.io/Salsah/documentation/guidelines/rst/app/view/modules/search/index.html?highlight=search).
