### ISSUE TITLE
SALSAH takes quite some time to load 

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#210]
When doing the initial request to SALSAH, it takes quite some time to load the page.

<img width="1920" alt="initial_load" src="https://user-images.githubusercontent.com/6000023/37389849-280d173c-2766-11e8-8dd2-fd6eb03df90f.png">

These files are quite big and should be minified for production:
- vendor.bundle.js
- main.bundle.js

**Comment by tobiasschweizer** [comment]
Probably the bottleneck is not the loading of the big JavaScript files but their evaluation in the browser.

**Comment by kilchenmann** [comment]
I made a performance check (in the web inspector) for one minute and get the following result:

![screen shot 2018-03-14 at 09 52 01](https://user-images.githubusercontent.com/4253580/37392143-9fe56c4e-276d-11e8-80a8-430ab81bd061.png)


But on my old Mac Mini it wasn't taking so long the load the page.

**Comment by subotic** [comment]
We build now with the `--prod` flag which is the best we can do for now

There are techniques involving lazy loading, which would break down the bundels into smaller once, which maybe could improve the loading time further. But this maybe requires to structure the application differently.

**Comment by tobiasschweizer** [comment]
@subotic For me the current solution is sufficient. There is already a huge difference to the non minified version. Thanks a lot for having taken care of this!

**Comment by subotic** [comment]
Your very welcome :-)
