### ISSUE TITLE
Styling issue in dialog

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#211]
On the Beol page I found a styling issue in the dialog box. We need a more space at the bottom of the dialog object viewer. It cuts the last pixels in the object viewer.

![screen shot 2018-03-14 at 09 56 27](https://user-images.githubusercontent.com/4253580/37392422-696aaaa2-276e-11e8-8355-5142afc3b163.png)

**Comment by tobiasschweizer** [comment]
Could we add more bottom padding in CSS for the dialog-content?

**Comment by kilchenmann** [comment]
Yes something like this. Can we do it tomorrow?

**Comment by kilchenmann** [comment]
The problem is the size of the dialog content. The calculation of max-height is wrong...
