### ISSUE TITLE
Generalization in v2 of the drag & drop feature of Salsah 1.0 for regions?

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Salsah#22]
I was just wondering if Salsah v2 will generalize the feature available for regions of interest since Salsah v1.

Currently, it is possible to drag & drop a ROI in a `TextValue` displayed in the GUI as a `Richtext`. We thought it would be useful for other resources as well, and not only ROI. Is it planned to implement something like this in v2?

It would be useful for `TextValue` but also, I think for `LinkValue`. Instead of searching in a field for the resource you want to link, draging and droping the resource (if it is already displayed in another window) you want to point to could be convenient.

**Comment by kilchenmann** [comment]
There's already a drag and drop function for linkValue in Salsah v1. But it's not yet self explained (and sometimes it doesn't work).
And indeed we need more drag and drop functionality. We will implement it in a better way in Salsah 2.

**Comment by mrivoal** [comment]
Thanks, André. I had no idea such a thing existed in v1.

**Comment by kilchenmann** [comment]
That's not your fault. The function is indeed really hidden.  Long time I didn't know about this function and I never used it. But Stephan showed it to me ;D

**Comment by musicEnfanthen** [comment]
And Lukas showed it to me ;D 
You can drag the open resource onto the green plus sign (+) of the link value, and it should be there.

**Comment by mrivoal** [comment]
Thanks, @musicEnfanthen. I will try it out.
