### ISSUE TITLE
Salsah releasing

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#222]
@subotic can you/we create a RELEASING.md file in the Salsah repository similar to [the one in Knora](https://github.com/dhlab-basel/Knora/blob/63d2d3e9afef8e23e2a262ccbbf3184d9cf89ba4/RELEASING.md) to know what to do or what you're doing. I'm sorry about the mistake today (All the notifications are and were turned on. Don't know what happend this morning.) and I want to help you with the releases in the future. Then I hope or I promise, it won't happen again. Thanks.

**Comment by sofiag** [comment]
Also sorry, @kilchenmann when you said "can I merge" I should have warned you but I thought you had seen it so I didn't say anything... @subotic can you let us know when you are done and we can resume merging? thx

**Comment by kilchenmann** [comment]
thanks @subotic . I will close this issue, because you wrote the REALISING file already in PR #223

**Comment by subotic** [comment]
No problem. I anyway wanted to suggest that you create releases for `Salsah`. Now that the process is more or less written down, it shouldn't be a problem. We can take a look at it next month for the next release if you like.

**Comment by kilchenmann** [comment]
Yes please.
