### ISSUE TITLE
Cursor for pointers to resources 

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#225]
We should use the CSS cursor property for links to other resources.

`src/app/view/properties/read-link-value/read-link-value.component.html`

```
<span matTooltip="{{valueObject?.getReferredResourceInfo(ontologyInfo)}}" (click)="showReferredResourceInDialog()">{{valueObject?.getContent()}}</span>
```

I guess we need to add a class and some CSS.

**Comment by kilchenmann** [comment]
there‘s already a global css class for links: .salsah-link

**Comment by tobiasschweizer** [comment]
Great, thanks for the hint!
