### ISSUE TITLE
Bug with OntologyInfoShort in project info

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#229]
After pull request in Knora ([#796](https://github.com/dhlab-basel/Knora/pull/796)?) the type OntologyInfoShort doesn't exist anymore in project. We have to update the project model in Salsah

**Comment by benjamingeer** [comment]
It was removed because it's no longer needed. Why do you see that as a bug? What problem is occurring?

**Comment by kilchenmann** [comment]
I had a type definition error in Salsah 2, because OntologyInfoShort doesn't exist anymore in Knora. And in Salsah we didn't update the project model. This is the reason, why i marked it as a bug.
I talked with @subotic about this topic and I try to fix it.

**Comment by benjamingeer** [comment]
OK, sorry, I didn't know that you modelled those things in SALSAH 2. Next time I'll let you know before the PR is merged.

**Comment by kilchenmann** [comment]
no problem.

**Comment by subotic** [comment]
My bad. I should have thought about this when I did the review. I will add running of `Salsah2` tests in the Knora repository. Those tests would have caught the problem.
