### ISSUE TITLE
Create ontology builder GUI

### ISSUE THREAD

**Issue by sofiag** [dhlab-basel/Salsah#241]
For adding new ontologies, resources and properties, we need an ontology builder. 
[ ] - split-screen-format, each side is: resource classes, properties, lists(?)
[ ] - possibility to select resource classes & properties from existing (public ontologies)

**Comment by kilchenmann** [comment]
No, we will have something like a split screen with on the left hand side the resource classes and on the right hand side the properties

**Comment by sofiag** [comment]
Yes, that's what I meant, I guess "tab" is the wrong word for it...

**Comment by kilchenmann** [comment]
easy

**Comment by sofiag** [comment]
Do you like the idea of using sidenav? Or rather grid list (with only columns?)

**Comment by sofiag** [comment]
Thanks Ben for the info!
And yes, there are no public ontologies right now, however we need to design the GUI so that it allows the usage also of future features as much as possible.

**Comment by sofiag** [comment]
The angular-split seems to provide much more flexibility and is more user-friendly than the sidenav:
https://bertrandg.github.io/angular-split/#/examples/dir-rtl
@kilchenmann you said you don't want to have many third-party modules, but this one seems to be worthwhile. Should I give it a try?

**Comment by kilchenmann** [comment]
There are many other split screen modules and we should compare them. I just found the angular-split by a quick search. We should looking for more. @sofiag can you collect some? And we need a module which allows to split the screen vertically but also horizontally. So we can reuse it in the resource compare view.

**Comment by sofiag** [comment]
this one does that (vertical & horizontal). It also allows to customise the way / direction of the split, and it gives options for drag-and-dropping the different parts into place. It is very customisable, that's why I thought it's very nice. I will collect some more and post them here.

**Comment by sofiag** [comment]
I found these, but I don't think we can get them for free... 
https://www.telerik.com/kendo-angular-ui/components/layout/splitter/
https://vaadin.com/components/vaadin-split-layout

I didn't find any free components that look better than the one mentioned in the message above e.g.:
https://www.jqwidgets.com/angular/angular-splitter/index.htm
https://angularscript.com/split-view-module-angular-2-split-pane/
https://github.com/angular-ui/ui-layout

(btw, For some reason plunkers do not work in my computer at home).
I have not tested any of them yet, this is all based on the options it offers and how it looks overall.

**Comment by kilchenmann** [comment]
Btw when I started with the salsah project, I tested an AngularJS resizable module, which made what we're looking for: https://codepen.io/kilchenmann/pen/jWyvNr
