### ISSUE TITLE
Missing services in @knora/core

### ISSUE THREAD

**Issue by flavens** [dhlab-basel/Salsah#272]
List of used and unused services in Salsah and missing in @knora/core.
> Need to clean it up

**Comment by flavens** [comment]
Services used

BasicOntologyService
BeolService
LanguageService
ResourceTypesService
StatusMsgService

—

Service seem 'unused'

FileService
PropertiesService
StoreService
TestService

**Comment by kilchenmann** [comment]
> Service seem 'unused'
FileService
PropertiesService
TestService

this can be removed;

**Comment by sofiag** [comment]
The basicOntologyService was based on a mock ontology we had made up at the beginning and is saved in Salsah. That was actually imitating an ontology of Knora v1 style. I don't think it is needed anymore, there are/ will be new services to get ontologies right?

**Comment by kilchenmann** [comment]
> Services used
BasicOntologyService
ResourceTypesService

we can keep this for the moment; perhaps we can also remove the component, where they are used; It's a part of new-resource-class and edit-resource-class, which should be moved to salsah-admin

>BeolService

should be moved to the own BEOL repository / presentation app

> LanguageService
StatusMsgService

we can keep this for the moment; we should move this to an own module or to the @knora/action module
