### ISSUE TITLE
Update KnoraConstants file

### ISSUE THREAD

**Issue by flavens** [dhlab-basel/Salsah#273]
Need to compare KnoraConstants.ts to AppConfig.ts, update KnoraConstants.ts and publish a new version of @knora/core

**Comment by flavens** [comment]
List of spotted missing variables (among several more):
- FileServer + AdminFileServer
- GNDPrefix + GNDResolver + VIAFPrefix + VIAFResolver
- SalsahLink

**Comment by kilchenmann** [comment]
What's the status of the issue?

**Comment by flavens** [comment]
after checking, this one is done > I close it
