### ISSUE TITLE
Lists admin component (without services)

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Salsah#28]
We need to be able to edit lists. Only the component. Services are in issue #240.

### Open points

- [x] Create new list
- [x] Add item to list
- [x] Rename list item
- [x] Reposition list item 
- [x] Delete list item if not in use
- [x] Restrict edit to project administrator
- [x] Edit nodes symbol appear on mouseover

**Comment by subotic** [comment]
Work-in-progress in PR #35

**Comment by subotic** [comment]
depends on: https://github.com/dhlab-basel/Knora/pull/572

**Comment by sofiag** [comment]
The checked points are now implemented, only create new list is still missing. However what is still necessary is to separate between logged-in user and/or administrator for these changes to be allowed. A user without permissions should only be able to see, but not edit the list. Is only an administrator of the project allow to edit?

**Comment by subotic** [comment]
> Is only an administrator of the project allow to edit?

Yes, at least this is how I have implemented the API.

**Comment by sofiag** [comment]
Create list form done in PR #185 
!Still need to fix the list services, Issues #195 and #209!

**Comment by sofiag** [comment]
@subotic these are all done now, can we close this issue?

**Comment by subotic** [comment]
I've renamed the issue, since only the component is finished.

**Comment by subotic** [comment]
you can close the issue

**Comment by sofiag** [comment]
There are several other issues about the services, and the latter are anyway not listed here at all. Ok, I will close it.
