### ISSUE TITLE
Adapt decimal and anyUri

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#281]
Changes introduced by https://github.com/dhlab-basel/Knora/pull/927 will require the following adaptions in SALSAH:

- JSON-LD conversion:
    - `DecimalValue` is now an object, not a string
    - `URIValue` is now an object, not a string

Check if the test data (both ontology and data) has to be updated.

**Comment by tobiasschweizer** [comment]
@kilchenmann @flavens @benjamingeer 

I think the migration to the new Salsah architecture takes more time than expected. I think we could just (redeundantly) apply the necessary changes to the Salsah repo as it is now (from https://github.com/dhlab-basel/Knora-ui/tree/wip/core-module-value-adaptation). Would that be ok?

**Comment by flavens** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [with Tobias: Adapt decimal and anyUri](https://trello.com/c/UkoLndHs/13-with-tobias-adapt-decimal-and-anyuri)
