### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#295]
After the upgrade to Angular 6 we should update the documentation especially the part about "app structure". For this documentation we use the Jekyll environment. But since the change of the default branch (from develop to master) and by using the docs folder in master branch, github says something about building issues because of css. 
![screen shot 2018-09-13 at 15 31 05](https://user-images.githubusercontent.com/4253580/45491528-33e71a00-b76a-11e8-9a87-d080c25377db.png)
At the moment I couldn't find the real issue here and I think, that I have to change something in the whole Jekyll template. So, when I have to change the template, why shouldn't we use the same, as we have for knora.org? So I will create a Salsah-docs landing-page (similar to knora.org), but then I will use the same template also for the documentation. Later we can use this (salsah)-documentation template also for the knora documentation.

**Comment by flavens** [comment]
@kilchenmann yes this is a great idea

**Comment by kilchenmann** [comment]
I started yesterday by taking the template from [Knora.org](https://github.com/dhlab-basel/Knora.org) and the one from [Salsah docs](https://github.com/dhlab-basel/Salsah/tree/master/docs/jekyll) and I tried to find a way how to mix them.
