### ISSUE TITLE
ng serve does not work

### ISSUE THREAD

**Issue by sofiag** [dhlab-basel/Salsah#3]
I can start the server with npm start, but not with ng serve. I get the message: "-bash: ng: command not found".
Generally the ng command does not work, also when I try to generate a component. 

I have freshly installed npm, but while installing @types/node and webpack-dev-server I get the warning:
"
salsah-2@2.0.0-alpha.1 /Users/sofia/Salsah
├── UNMET PEER DEPENDENCY webpack@>=1.3.0 <3
└── webpack-dev-server@1.16.2 

npm WARN webpack-dev-server@1.16.2 requires a peer of webpack@>=1.3.0 <3 but none was installed.
"
but I don't get any errors.

**Comment by loicjaouen** [comment]
`ng: command not found`:
did you install https://github.com/angular/angular-cli ?

**Comment by sofiag** [comment]
You’re right, I forgot it, thanks!

——————————————————
Dr. Sofia Georgakopoulou
Digital Humanities Lab
University of Basel
Bernoullistrasse 32,
4056 Basel, Switzerland
tel: +41 61 207 09 09
email: s.georgakopoulou@unibas.ch
——————————————————
