### ISSUE TITLE
Since a few commits ago, Salsah seems to not be able to connect to Knora

### ISSUE THREAD

**Issue by janCstoffregen** [dhlab-basel/Salsah#42]
Dear Reader,
I get the following error message:

Error: Fatal error in JsonConvert. Failed to map the JSON object to the class "ProjectsList" because of a type error.

	Class property: 
		projects

	Expected type: 
		[ProjectItem]

	JSON property: 
		projects

	JSON type: 
		[object,object,object,object,object,object,object,object]

	JSON value: 
		[{"shortname":"biblio","description":"Bibliography","belongsToInstitution":null,"logo":null,"dataNamedGraph":"http://www.knora.org/data/biblio","id":"http://data.knora.org/projects/DczxPs-sR6aZN91qV92ZmQ","status":true,"keywords":null,"longname":"Bibliography","ontologyNamedGraph":"http://www.knora.org/ontology/biblio","hasSelfJoinEnabled":false},{"shortname":"lombardus","description":"Lombardus Project","belongsToInstitution":null,"logo":null,"dataNamedGraph":"http://www.knora.org/data/lombardus","id":"http://data.knora.org/projects/lombardus","status":true,"keywords":null,"longname":"Lombardus Project","ontologyNamedGraph":"http://www.knora.org/ontology/lombardus","hasSelfJoinEnabled":false},{"shortname":"beol","description":"Bernoulli-Euler Online","belongsToInstitution":null,"logo":null,"dataNamedGraph":"http://www.knora.org/data/beol","id":"http://data.knora.org/projects/yTerZGyxjZVqFMNNKXCDPF","status":true,"keywords":null,"longname":"Bernoulli-Euler Online","ontologyNamedGraph":"http://www.knora.org/ontology/beol","hasSelfJoinEnabled":false},{"shortname":"incunabula","description":"<p>Das interdisziplinäre Forschungsprojekt \"<b><em>Die Bilderfolgen der Basler Frühdrucke: Spätmittelalterliche Didaxe als Bild-Text-Lektüre</em></b>\" verbindet eine umfassende kunstwissenschaftliche Analyse der Bezüge zwischen den Bildern und Texten in den illustrierten Basler Inkunabeln mit der Digitalisierung der Bestände der Universitätsbibliothek und der Entwicklung einer elektronischen Edition in der Form einer neuartigen Web-0.2-Applikation.\n</p>\n<p>Das Projekt wird durchgeführt vom <a href=\"http://kunsthist.unibas.ch\">Kunsthistorischen Seminar</a> der Universität Basel (Prof. B. Schellewald) und dem <a href=\"http://www.dhlab.unibas.ch\">Digital Humanities Lab</a> der Universität Basel (PD Dr. L. Rosenthaler).\n</p>\n<p>\nDas Kernstück der digitalen Edition besteht aus rund zwanzig reich bebilderten Frühdrucken aus vier verschiedenen Basler Offizinen. Viele davon sind bereits vor 1500 in mehreren Ausgaben erschienen, einige fast gleichzeitig auf Deutsch und Lateinisch. Es handelt sich um eine ausserordentlich vielfältige Produktion; neben dem Heilsspiegel finden sich ein Roman, die Melusine,  die Reisebeschreibungen des Jean de Mandeville, einige Gebets- und Erbauungsbüchlein, theologische Schriften, Fastenpredigten, die Leben der Heiligen Fridolin und Meinrad, das berühmte Narrenschiff  sowie die Exempelsammlung des Ritters vom Thurn.\n</p>\nDie Internetpublikation macht das digitalisierte Korpus dieser Frühdrucke  durch die Möglichkeiten nichtlinearer Verknüpfung und Kommentierung der Bilder und Texte, für die wissenschaftliche Edition sowie für die Erforschung der Bilder und Texte nutzbar machen. Auch können bereits bestehende und entstehende Online-Editionen damit verknüpft  werden , wodurch die Nutzung von Datenbanken anderer Institutionen im Hinblick auf unser Corpus optimiert wird.\n</p>","belongsToInstitution":null,"logo":"incunabula_logo.png","dataNamedGraph":"http://www.knora.org/data/incunabula","id":"http://data.knora.org/projects/77275339","status":true,"keywords":"Basler Frühdrucke, Inkunabel, Narrenschiff, Wiegendrucke, Sebastian Brant, Bilderfolgen, early print, incunabula, ship of fools, Kunsthistorischs Seminar Universität Basel, Late Middle Ages, Letterpress Printing, Basel, Contectualisation of images","longname":"Bilderfolgen Basler Frühdrucke","ontologyNamedGraph":"http://www.knora.org/ontology/incunabula","hasSelfJoinEnabled":false},{"shortname":"anything","description":"Anything Project","belongsToInstitution":null,"logo":null,"dataNamedGraph":"http://www.knora.org/data/anything","id":"http://data.knora.org/projects/anything","status":true,"keywords":null,"longname":"Anything Project","ontologyNamedGraph":"http://www.knora.org/ontology/anything","hasSelfJoinEnabled":false},{"shortname":"SystemProject","description":"Knora System Project","belongsToInstitution":null,"logo":null,"dataNamedGraph":"-","id":"http://www.knora.org/ontology/knora-base#SystemProject","status":true,"keywords":null,"longname":"Knora System Project","ontologyNamedGraph":"http://www.knora.org/ontology/knora-base","hasSelfJoinEnabled":false},{"shortname":"dokubib","description":"Dokubib","belongsToInstitution":null,"logo":null,"dataNamedGraph":"http://www.knora.org/data/dokubib","id":"http://data.knora.org/projects/b83b99ca01","status":false,"keywords":null,"longname":"Dokubib","ontologyNamedGraph":"http://www.knora.org/ontology/dokubib","hasSelfJoinEnabled":false},{"shortname":"images","description":"A demo project of a collection of images","belongsToInstitution":null,"logo":null,"dataNamedGraph":"http://www.knora.org/data/images","id":"http://data.knora.org/projects/images","status":true,"keywords":"images, collection","longname":"Image Collection Demo","ontologyNamedGraph":"http://www.knora.org/ontology/images","hasSelfJoinEnabled":false}]

Fatal error in JsonConvert. Failed to map the JSON object to the class "ProjectItem" because the defined JSON property "institution" does not exist:

	Class property: 
		institution

	JSON property: 
		institution
    at Function.JsonConvert.deserializeObject_loopProperty (json-convert.ts:234)
    at Function.JsonConvert.deserializeObject (json-convert.ts:133)
    at ApiServiceResult.getBody (api-service-result.ts:50)
    at SafeSubscriber._projectsService.getAllProjects.subscribe._this.errorMessage [as _next] (projects-list.component.ts:72)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at CatchSubscriber.Subscriber._next (Subscriber.js:125)
    at CatchSubscriber.Subscriber.next (Subscriber.js:89)
core.es5.js:1020 ERROR TypeError: Cannot read property 'projects' of null
    at SafeSubscriber._projectsService.getAllProjects.subscribe._this.errorMessage [as _next] (projects-list.component.ts:72)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at CatchSubscriber.Subscriber._next (Subscriber.js:125)
    at CatchSubscriber.Subscriber.next (Subscriber.js:89)
    at MapSubscriber._next (map.js:83)
    at MapSubscriber.Subscriber.next (Subscriber.js:89)
    at XMLHttpRequest.onLoad (http.es5.js:1226)
defaultErrorLogger @ core.es5.js:1020
ErrorHandler.handleError @ core.es5.js:1080
next @ core.es5.js:4562
schedulerFn @ core.es5.js:3635
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3621
NgZone.triggerError @ core.es5.js:3993
onHandleError @ core.es5.js:3954
webpackJsonp.736.ZoneDelegate.handleError @ zone.js:395
webpackJsonp.736.Zone.runTask @ zone.js:194
ZoneTask.invoke @ zone.js:486

It does not show the projects and is stuck at loading. This happens after a fresh git clone from Salsah and a fresh version from Knora. With previous versions of Salsah everything works fine.

I am sorry but I don't know after which commit this happened. Are you aware of this?

Thank you so much for your answer and best regards,
Jan

**Comment by aeneaskaiser** [comment]
Hi, i'm currently not working on the `develop` branch, but if i'm not mistaken:

you would have to use the `wip/admin-api-4` branch from Knora to be compatible with the `develop` branch from Salsah.

Pinging @subotic, since he knows better than me.

**Comment by subotic** [comment]
Yes, we are aware. At the moment, you need to use the `wip/admin-api-4` branch of `knora`. I need to do some finishing touches on this branch (no new features, just tests) before we can merge it back to `develop`. The initial idea was to do the merge two weeks ago, but other stuff kept creeping up.

Hopefully, I will have the PR https://github.com/dhlab-basel/Knora/pull/486 ready next week. From then on, `develop` should work fine again.

**Comment by subotic** [comment]
@aeneaskaiser you where faster :-)

**Comment by janCstoffregen** [comment]
Thank you both so much for your answer, I know it now and can use the versions accordingly.
Best regards,
Jan

**Comment by janCstoffregen** [comment]
Ok, I will close this issue since it has been answered, sorry for the late closure. 
Best regards,
Jan
