### ISSUE TITLE
local storage needs to be somehow mocked for tests

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#46]
A few components (ProjectResourceComponent, ProjectTeamComponent, UserProjectsComponent, HeaderToolbarComponent) require the user to be logged in or a project selected. This information is stored inside localStorage.

**Comment by musicEnfanthen** [comment]
Maybe you can find some hints here?

https://stackoverflow.com/questions/35033694/how-to-unit-test-an-angularjs-service-that-uses-localstorage-internally

https://gist.github.com/wzr1337/b3fe4abcc46588aa8fcb

With some explanations: http://ngokevin.com/blog/angular-unit-testing/

**Comment by kilchenmann** [comment]
fixed in PR #47

**Comment by subotic** [comment]
Just a side note. I would close an issue only when the changes hit `develop`. When you write in a comment on a pull request `resolves #46`, then the issue will be closed automatically by Github, when the PR is merged.
