### ISSUE TITLE
Maybe we should add `package-lock.json` into the repository

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Salsah#49]
As I have found out just now, there is this `package-lock.json` file. According to the npm [documentation](https://docs.npmjs.com/files/package-lock.json), it is recommended, to add this file to the repository. As I understand it, we would gain the ability for controlled library updates, i.e. this file guarantees to install exactly the same dependency tree, even if some library had an update in the meantime.

**Comment by sofiag** [comment]
If I'm not wrong, it is now installed automatically if you update / install npm. I did it recently and the lock file appeared. In fact I didn't know what it was :-) ...

**Comment by subotic** [comment]
@kilchenmann any thoughts on this?

**Comment by kilchenmann** [comment]
I will have a look on that...

**Comment by kilchenmann** [comment]
It creates the package-lock.json when you update your node modules with `npm update`. This command updates the packages in node_modules but it will not change the version in package.json.

To update the package.json automatically I suggest to install the [npm-check-updates](https://www.npmjs.com/package/npm-check-updates).

I will have a deeper look on the just generated package-lock.json file. I will push it with my current branch [wip/team-and-user](https://github.com/dhlab-basel/Salsah/tree/wip/team-and-user)

**Comment by kilchenmann** [comment]
Since December 2017 we're using yarn instead of npm which resolves this issue by adding yarn.lock. It works better than the suggested package-lock.json
