### ISSUE TITLE
How to deal with URL citation needs in Salsah 2.0 ?

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Salsah#5]
How are we planning to display the URL of resources in the GUI? 

In the previous version of Salsah, it was possible to see the ID of a resource by moving over the resource label with the mouse. 

I think in Salsal 2.0, the URL of a resource should also be displayed somewhere, and I also think that the user should be able to copy-paste it easily.

This is probably going to be a user requirement soon. What do you think about it?

**Comment by lrosenth** [comment]
Hi Marion,

Yes, indeed we need this absolutely!! I'll see that it will work with the old GUI..

Thanks for this important hint!!

Lukas

Sent from my iPad

On 8 Dec 2016, at 12:23, Marion Rivoal <notifications@github.com<mailto:notifications@github.com>> wrote:


How are we planning to display the URL of resources in the GUI?

In the previous version of Salsah, it was possible to see the ID of a resource by moving over the resource label with the mouse.

I think in Salsal 2.0, the URL of a resource should also be displayed somewhere, and I also think that the user should be able to copy-paste it easily.

This is probably going to be a user requirement soon. What do you think about it?

**Comment by kilchenmann** [comment]
We will use the "share" button to display the url. There's a short sentence about that issue in the developer guidelines:
https://dhlab-basel.github.io/Salsah/documentation/guidelines/rst/salsah2/components/salsahObject.html

**Comment by mrivoal** [comment]
Great! Thanks!

And thank you André for redirectring me to Salsah 2.0 online documentation. I didn't know it existed.
