### ISSUE TITLE
Use v2 in develop

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#74]
We think it would be a good idea to merge `integrate-v2` into `develop`. However, we should think about how making consistent use of api v2 first.

Currently, v1 and v2 are used in parallel. Can we get rid of v2 and only use v2 instead?

**Comment by tobiasschweizer** [comment]
I have already added a v2 service to read ontologies: `src/app/model/services/ontology.service.ts`. 

And this v2 service caches the information: `src/app/model/services/ontologycache.service.ts`

Can this be unified with what you do on `develop` for ontologies?

**Comment by kilchenmann** [comment]
- The Salsah admin is still using the Knora v1. This could be a problem when you want to rid of v1. @subotic has to implement / or move the v1 admin stuff into the v2.
- On develop there's no real ontologies service from my side. It's a fake service which uses a simple json file. Here we have to wait for @benjamingeer's work.

**Comment by tobiasschweizer** [comment]
Could we at least organize services and components etc. in a v1/v2 directory structure?
