### ISSUE TITLE
ngIf / else for error messages and loader

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#83]
We should use *ngIf / else with ng-template to handle the error messages and progress loader view.
(instead of a lot of *ngIf directives)

**Comment by andreas-aeschlimann** [comment]
In my experience, readability is quite horrible with the new `if/else` syntax, so I dropped the idea and stayed with a lot of `if`.

Also, I replaced all occurrences of `<ng-template>` with `<ng-container>`, because the template does not support the usual Angular syntax.

```
// Unlogical and weird syntax
<ng-template [ngIf]="bla">
</ng-template>

// Usual syntax as for all normal tags
<ng-container *ngIf="bla">` 
</ng-container>

```

The same applies for the weird `[ngFor]` that is needed with `<ng-template>`, where you can use the usual `*ngFor` with `<ng-container>`.

**Comment by kilchenmann** [comment]
I'm using the ng-template only for the else case

```
<div *ngIf="results > 0; else noData">
    <!-- show the data here -->
</div>

<ng-template #noData>
   <!-- no results found message -->
</ng-template>

**Comment by tobiasschweizer** [comment]
I have a question regarding error handling: Can we make our own subclasses of `Error` and throw them when necessary? 

Example for `OntolgyCacheService`:

```
/**
 * Represents an error occurred in OntologyCacheService.
 */
class OntologyCacheError extends Error {

    constructor(readonly message: string) {
        super(message)
    }

}
```

Then subsequently instances of this class can be created with an apt message describing the problem that occurred.

**Comment by kilchenmann** [comment]
At the moment I have the salsah-message-component, which handles the error (and also warnings and notes) and shows the message which I get from the API. With the status code (404, 300, etc.) we grab the default message and a description from the statusMsg.json file from assets/i18n/ — btw. i18n stands for internationalization (s. [Wiki](https://en.wikipedia.org/wiki/Internationalization_and_localization)) and will be used to store the language files for the ui.
But which data do we receive, when an error occured? At the moment I get only a short status message from the Knora API? Do we really need an additional cache service for that?

**Comment by tobiasschweizer** [comment]
The thing is that in case of the `OntologyCacheService` the error does not directly come from the API. An error is thrown when an information cannot be found in the cache which should be there.

Example: the client asks the ontology responder for a `incunabula:book` which returns both the cardinalities for its properties and also the definitions of these properties. Later the 
`OntologyCacheService` is asked for  a `incunabula:book`, finds out that it already has the information about it but does not find the property it should already have received in an earlier request to the API.

**Comment by kilchenmann** [comment]
okay I see. I don't know very well your cache service. So, if you like you can implement an OntologyCacheError? ...

**Comment by tobiasschweizer** [comment]
I already did :-)

See <https://github.com/dhlab-basel/Salsah/blob/b4758123c5598e749c542d7ddbc86b9fd86e3d3d/src/app/model/services/ontologycache.service.ts#L13>

Where the error is handled, it could get the error message and print it out.
