### ISSUE TITLE
Edit resource update

### ISSUE THREAD

**Issue by sofiag** [dhlab-basel/Salsah#90]
In edit resource properties, change the style from a tab with a horizontal navigation, to vertical expandable cards, one for each property, in the style of "add users". Each card has its own save button.

**Comment by kilchenmann** [comment]
I saw just right now the PR #93 for this issue. Is it already done? It would be great if we can merge it as soon as possible.

**Comment by sofiag** [comment]
This is done, yes. However, not using reactive forms. I implemented reactive forms (with FormBuilder) in the resource edit part, but not yet in the property edit part and the add property part. However, the style edit of this issue is completed. Once we merge I will make a new issue, to change the edit/add properties part to use reactive forms and take it from there.
