### ISSUE TITLE
error in ontologies route when querying images ontology

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#95]
http://localhost:3333/v2/ontologies/namedgraphs/http%3A%2F%2F0.0.0.0%3A3333%2Fontology%2Fimages%2Fv2

```
{
status: 4,
error: "org.knora.webapi.InconsistentTriplestoreDataException: Unsupported rdf:type for property: http://www.w3.org/2002/07/owl#Class"
}
```

However, this works fine: http://localhost:3333/v2/ontologies/namedgraphs/http%3A%2F%2F0.0.0.0%3A3333%2Fontology%2Fincunabula%2Fv2

**Comment by benjamingeer** [comment]
This is because there is a property `images:bildformat` and a class `images:bildformat`. This is something we should forbid.

**Comment by benjamingeer** [comment]
Fixed in https://github.com/dhlab-basel/Knora/pull/649.
