### ISSUE TITLE
Add compatibility changes to 'projects-service'

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Salsah#97]
Add needed changes so that the GUI works with changes introduced in https://github.com/dhlab-basel/Knora/pull/659

**Comment by kilchenmann** [comment]
- [x] We have to change the project item class in the ui service. The Knora API will change... ontologyNamedGraph and dataNamedGraph will be merged into an array called ontologies. 
- [ ] Changing the templates and the ts files where the ontologyNamedGraph and dataNamedGraph are used

Btw I can do that

**Comment by subotic** [comment]
The PR https://github.com/dhlab-basel/Knora/pull/659 is more or less ready for review.

We could now do the necessary changes. Do you already have a branch for these changes?

**Comment by subotic** [comment]
PR https://github.com/dhlab-basel/Knora/pull/659 is merged.

**Comment by kilchenmann** [comment]
Great news. Yes I have already a branch for these changes: [wip/fix-issue#97](https://github.com/dhlab-basel/Salsah/tree/wip/fix-issue%2397)

**Comment by kilchenmann** [comment]
Most of the projects in the knora test data doesn't have a shortcode (it's alway null). The only one with a shortcode is the "images" project (00FF). But anyway, do I need the shortcode just right now in Salsah? Who adds the shortcode? I think it's an automatic generated one by Knora?

**Comment by kilchenmann** [comment]
I had to move/merge the branch from [wip/fix-issue#97](https://github.com/dhlab-basel/Salsah/tree/wip/fix-issue%2397) to [wip/fix-issue#99](https://github.com/dhlab-basel/Salsah/tree/wip/fix-issue%2399)

**Comment by subotic** [comment]
Yes, at the moment only `images` has a shortcode defined. The `shortcode` needs to be supplied at the time of project creation. At the moment, the `shortcode` is optional, because not all our test data have it, but it is actually required for every **new** project. So in the GUI for project creation, it should be required.

The shortcode is a 4 digit hexadecimal number (`0000` - `FFFF`) at least for now (see https://github.com/dhlab-basel/Knora/issues/664).

The projects `0000` to `00FF` are used for test purposes. In the beginning, Unil will use the project numbers `0100`-`07FF` , and Unibas `0800` - `08FF`. We should keep a list somewhere.

Each shortcode needs to be unique.
