### ISSUE TITLE
ontologies

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#99]
A project can have more than one ontology (when issue #97 is done). So we need an additional tab or a replacement for the "resources" tab. And we need a button to add more ontologies.

The webapi isn't ready yet to create ontologies in a direct way, but we need a solution right now. As @lrosenth suggested, we have to work with turtle (ttl) files. It means, that we need a translation layer to get json from turtle or to create turtle from json. The solution could be N3 which can handle this.

Todo:
- [x] New tab for ontologies incl. add button

**Comment by sofiag** [comment]
In the edit resource part you can chose the ontology where your property (should) belong. We then maybe just need to add a drop-down menu to select ontologies in the add resource part.

**Comment by kilchenmann** [comment]
The webapi isn't ready yet to create ontologies in a direct way, but we need a solution right now. As @lrosenth suggested, we have to work with turtle (ttl) files. It means, that we need a translation layer to get json from turtle or to create turtle from json. The solution could be [N3](https://www.npmjs.com/package/n3) which can handle this.

Todo:
- [ ] New tab for ontologies incl. add button
- [ ] New list for ontologies
- [ ] Implement N3 library
- [ ] Create default base ontology (as we already did with the json file in the app, but we have to make it better)
- [ ] Form to create new ontology
- [ ] Form to edit ontologies

**Comment by musicEnfanthen** [comment]
Why not using JSON-LD directly?

Otherwise this [RDFTranslator](http://rdf-translator.appspot.com/) could be useful?

**Comment by kilchenmann** [comment]
What do you mean with json-ld directly. At the moment we can‘t work with ontologies from the knora api direct way, but we need a quick solution now. So the idea is, that we get turtle files from the database and we send turtle files back to the database. This is just to create new or to edit ontologies until Knora is ready.
I will have a detailed look on the api of your suggested RDF Translator... thanks

**Comment by subotic** [comment]
I think what @musicEnfanthen means is that instead of getting the `ttl` file from the triplestore, we get a `json-ld` file. Maybe it is easier to work with a `json-ld` than with `turtle` in typescript?

**Comment by subotic** [comment]
@kilchenmann I would put the todo at the top of the issue. By doing so, the first post can figure as a summary of the whole discussion and highlight any decisions taken.

**Comment by kilchenmann** [comment]
Okay I see. Yes why not json-ld? If you @subotic can handle it serverside incl. post and put... for me it doesn't matter

**Comment by musicEnfanthen** [comment]
> I think what @musicEnfanthen means is that instead of getting the ttl file from the triplestore, we get a json-ld file. Maybe it is easier to work with a json-ld than with turtle in typescript?

Yes, exactly. Since every valid `json-ld` is valid `json` too, it should be much easier to handle than transforming from `ttl` to `json`. By the way, I thought that KNORA is delivering the ontologies in `json-ld` format, isn't it? If so, this approach would also be closer to KNORA's real API answer that the GUI has to handle later on.
